### PR TITLE
add key definitions

### PR DESCRIPTION
**Pull request by lmk123**
Add `CtrlRight`、`ShiftRight`、`AltRight`、`Meta` and `MetaRight`.

Source:

https://github.com/kwhat/libuiohook/blob/1.2/include/uiohook.h#L289-L299

### CODE REVIEW

**Comment by arctan95** [comment]
@lmk123  @SnosMe  This PR is incorrect: the hexadecimal code for 'Meta' is 0xE05B, not 0x0E5B. Check others.

See: https://libvirt.org/manpages/virkeycode-atset1.html

Snipaste_2025-04-12_15-41-42

**Comment by SnosMe** [comment]
@arctan95 yeah looks like keycodes were inspired by libvirt. But this typo by library author doesn't matter, all remaping happens in [%platform%/input_helper.c](https://github.com/search?q=repo%3Akwhat%2Flibuiohook+VC_META_L&type=code), the authoritative file for keycodes is uiohook.h not the libvirt.

**Comment by arctan95** [comment]
So is the keycode here platform-independent? Then if I want to use uiohook-napi to get the scancode for each platform, is that impossible?

**Comment by SnosMe** [comment]
Yes, it's platform-independent, there's also a `rawcode` but I don't expose it in JS bindings yet (easy to add).

https://github.com/kwhat/libuiohook/blob/2a2d40f96178481d98980da0a8c1db8a41937d7c/include/uiohook.h#L88-L92

**Pull request merged**
